### ISSUE TITLE
Cart Form Validation

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/Kanap#1]
cc @Tomerozfresko 

Right now there is some opportunity to make the form validation functionality a bit more DRY.

What if your individual validators returned the valid string if it passes the regex test? In that way you would be [setting the constants](https://github.com/Tomerozfresko/Kanap/blob/master/front/js/cart.js#L212-L220) with either `false` (for invalid values) or the validated `string` that's going to be saved in the contact object. 

Then [your conditional](https://github.com/Tomerozfresko/Kanap/blob/master/front/js/cart.js#L221) would remain the same, and instead of having an intermediary `createContact` function, you can pass all the strings as an object literal straight into your `sendOrder` function.

So if your validators did some thing like this:

```js
function addressValidation(city){
    var regName = /^[a-z0-9\s,'-]*$/i;
    //names like Mathias d'Arràs || Martin Luther King, Jr. are accepted
    if (!regName.test(city) || city === "") {
        addressErrorMsg.innerHTML = "Please enter valid address.";
        return false;
    } else {
        return city; // returning a valid string
    }
}
```

and your validate form function did something like this:

```js
function formValidation(event) {
    ...
    //email
    const email= emailValidation(document.querySelector('#email').value);
    //Names 
    const firstName = firstNameValidation(document.querySelector('#firstName').value)
    const lastName = nameValidation(document.querySelector('#lastName').value)
    //location
    const address = addressValidation(document.querySelector('#address').value)
    const city = cityValidation(document.querySelector('#city').value)
    
    if (email && firstName && lastName && address && city && getCart().length != 0) {

        sendOrder({
            email, // this is shorthand for email: email, since "email" is already declared in this scope
            firstName,
            lastName,
            address,
            city
        });
    }
```

This would be a little more dry as it reduced the number of time you're query'ing for the DOM elements and removes the need for a createConact function.

One last thing you can do, also, is to return false in your first conditional (if the cart is empty) so you don't have to check for the cart length a second time in the `formValidation` function.

**Comment by Tomerozfresko** [comment]
cc @AccessiT3ch  

Thank you! great idea's. 
Done and committed.

**Comment by AccessiT3ch** [comment]
@Tomerozfresko I was able to use a non-valid email ("asdf") to submit the Cart form, it definitely looks like the regex test is working as expected, but what is being returned in the if/else should be flipped. (currently the email is being returned when the regex fails)

**Comment by Tomerozfresko** [comment]
@AccessiT3ch 
Tnx, it should be fine now :)
