### ISSUE TITLE
Add to Cart Success Indicator

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/Kanap#3]
@Tomerozfresko - I'm not sure if this is specified in the specs, and it does not look like it is a requirement in the rubric, but usually there should be some sort of success indicator when executing a function (in this case, adding something to the cart). Currently, as a user (without my console open), I don't know if my items were added to the cart, which can be a little confusing. In this case, I think you could either render a little success message under the Add to cart button or use an alert like you are doing in other places.

So nothing required here to pass, just noting a best practice!

**Comment by Tomerozfresko** [comment]
Sure thing! 
Done.
