### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/Kanap#4]
@Tomerozfresko - There is a specific success criteria about comments:

```
Each function is described, at the start, with a comment
```

For the most part it looks like there are comments, though there are a few that don't have any, so do be sure go through and add descriptive comments to all your functions. A few thoughts on best practices here:

```js
// Descriptive Function Name
```
I think this is basically the minimum viable implementation of this requirement (and for collaborating with other devs), though it can very nice to explicitly describe the function parameters and return values. It looks like you're already starting to do this for some functions, and it may be nice to do it for all of them as these comments will help provide VS Code with more helpful hints and tooltips.

```js
// Good

/**
* Function description
* @param {type} parameterName
* @returns {type|type}
**/


// Better

/**
* Function description
* @param {type} parameterName - description of the parameter
* @returns {type|type} description of what is returned (type: void if no return)
**/


// Extra (and useful when generating docs!)

/**
* Function description
* @param {type} parameterName - description of the parameter
* @returns {type|type} description of what is returned (type: void if no return)
* @example const something = anExampleFunction("foo")
**/


```

**Comment by Tomerozfresko** [comment]
Thank you, this is noted. 
Please have another look, i committed a more "documented" version.
